<?php
// $Id: eml_config.module, v 2.0 2010-11-22 ashipunova $
/*
 * Form for eml settings, required by views_bonus_eml_export
 * ?q=eml_config
*/

require_once("csv2drupal.inc");

function csv2drupal_menu() {

  $items = array();
  $items['csv2drupal'] = array (
    'title' => t('Export CSV files into predefined custom content types for the LTER project'),
    'page callback' => 'csv2drupal_page',
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
//    'file' => 'csv2drupal_form.inc',
    );
  return $items;
}

function csv2drupal_page() {
  return drupal_get_form('eml_config_form');
}

function eml_config_form($form_state) {
  $form['#attributes']['enctype'] = 'multipart/form-data';

  $form['upload'] = array(
   '#type' => 'file',
   '#title' => t('Upload Excel file'),
   '#size' => 40,
  );

  $form['submit'] = array (
  '#type' => 'submit',
  '#value' => t('Upload'),
  );

  return $form;
}

function eml_config_form_submit($form, &$form_state) {
  $file = file_save_upload('upload');
  if ($file) {
    $dest_path = file_directory_path() . '/upload';
//    $result = file_copy($file, $dest_path, FILE_EXISTS_RENAME);
    $result = file_copy($file, $dest_path, FILE_EXISTS_REPLACE);

    if ($result) {
      $filepath = $file->filepath;
      $content = get_data_from_excel_file($filepath);
      create_nodes($content);
      dpr($content);
    }
  }
  else {
    form_set_error('eml_config_form', t("Failed to save the file."));
  }
}
